# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove missing numeric values in objects
.na.omit <- function(x) {
    .Call('_WRShd_na_omit', PACKAGE = 'WRShd', x)
}

#' Compute the Harrell-Davis estimate of the qth quantile
.hd <- function(x, q = 0.5, na_rm = TRUE, cores = 1L) {
    .Call('_WRShd_hd', PACKAGE = 'WRShd', x, q, na_rm, cores)
}

#' Compute a bootstrap standard error of the Harrell-Davis estimate of the qth quantile
.hdseb <- function(x, q = 0.5, nboot = 100L, cores = 1L) {
    .Call('_WRShd_hdseb', PACKAGE = 'WRShd', x, q, nboot, cores)
}

#' Compute a 1-alpha confidence for the Harrell-Davis estimate of the qth quantile
.hdci <- function(x, q = 0.5, nboot = 100L, pr = TRUE, cores = 1L) {
    .Call('_WRShd_hdci', PACKAGE = 'WRShd', x, q, nboot, pr, cores)
}

#' Compute a bootstrap 1-alpha confidence for the Harrell-Davis estimate of the qth quantile
.hdpb <- function(x, q = 0.5, alpha = 0.05, nboot = 2000L, nv = 0, cores = 1L) {
    .Call('_WRShd_hdpb', PACKAGE = 'WRShd', x, q, alpha, nboot, nv, cores)
}

.qcom.sub <- function(x, y, q, alpha = 0.05, nboot = 2000L, cores = 1L) {
    .Call('_WRShd_qcom_sub', PACKAGE = 'WRShd', x, y, q, alpha, nboot, cores)
}

