# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove missing numeric values in objects
#' 
#' @param x a numeric \code{vector}
#' @return a numeric vector w/o NAs
.na.omit <- function(x) {
    .Call('WRS2_na_omit', PACKAGE = 'WRS2', x)
}

#' Compute the Harrell-Davis estimate of the qth quantile
#' 
#' @param x a numeric \code{vector}
#' @param q a desired quantile
#' @param cores a number of cores used
#' @return the Harrell-Davis estimate of the \code{q}-th quantile of \code{x}
hd <- function(x, q, cores = 1L) {
    .Call('WRS2_hd', PACKAGE = 'WRS2', x, q, cores)
}

#' Compute a bootstrap standard error of the Harrell-Davis estimate of the qth quantile
#' 
#' @param x a numeric \code{vector}
#' @param q a desired quantile
#' @param nboot a number of bootstraps
#' @param cores a number of cores used
#' @return the standard error of the Harrell-Davis estimate of the qth quantile
hdseb <- function(x, q = 0.5, nboot = 100L, cores = 1L) {
    .Call('WRS2_hdseb', PACKAGE = 'WRS2', x, q, nboot, cores)
}

#' Compute a bootstrap confidence interval for the Harrell-Davis estimate of the qth quantile
#' 
#' @param x a numeric \code{vector}
#' @param q a desired quantile
#' @param alpha a significance level
#' @param nboot a number of bootstraps
#' @param nv a null-value when computing a p-value
#' @param cores a number of cores used
#' @return the confidence inteval
hdpb <- function(x, q, alpha = 0.05, nboot = 2000L, nv = 0, cores = 1L) {
    .Call('WRS2_hdpb', PACKAGE = 'WRS2', x, q, alpha, nboot, nv, cores)
}

.qcom.sub <- function(x, y, q, alpha = 0.05, nboot = 2000L, cores = 1L) {
    .Call('WRS2_qcom_sub', PACKAGE = 'WRS2', x, y, q, alpha, nboot, cores)
}

